### ISSUE TITLE
React Auth Sample login Issue

### ISSUE THREAD

**Issue by michal-petrik** [OfficeDev/PnP-OfficeAddins#100]
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth/Office-Add-in-Microsoft-Graph-React

**Describe the bug**

I followed the sample, however, the login process in popup window fails. Using debugger the error is:
`AcquireToken_In_Progress: Error during login call - login is already in progress.`
Then there are many cyclic redirects and the whole process failure at the end.

**To Reproduce**

Steps to reproduce the behaviour:
1. Download the sample https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth/Office-Add-in-Microsoft-Graph-React
2. Follow the instructions and try to Run the project
3. Push "Connect to Office 365" button

**Expected behaviour**

User is correctly logged in and the sample lists OneDrive files.

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: 2016 (16.0.5071.1000)
- Operating System: Windows 10 Enterprise 2016 LTSB
- Browser (if using Office Online): N/A

**Additional context**
Of course, the requirements say I need Excel version 16.0.6769.2001+ and I have  16.0.5071.1000. However, is it really the case? It seems the sample is using an older MSAL version. Is it an IE issue? For example, the following sample is working correctly in my environment: https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/

**Comment by Rick-Kirkham** [comment]
@davidchesnut is our auth guy. In the meantime, here are some thoughts that might help: 

You definitely have to use the required version of Office. Even when you get past the problem you are seeing now, you would get errors later in the process. So the first step is to upgrade your Office. 

msal.js 1.0 uses LocalStorage and its handling of LocalStorage is buggy. Those bugs can lead to the kind of symptoms that you are having. 

Each domain has its own LocalStorage. When your add-in is running, open it's home page in a browser. Use your browser's F11 tools to go to the LocalStorage for the add-in's domain and delete everything in the domain's LocalStorage. 

For good measure, clear the cache of the browser that Office uses for the task pane. (See [Browsers used by Office add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) to find out which browser it uses.) and delete the Office cache too. See [Clear the Office cache](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache).

Then reboot and try the sample again. 

We probably should update this sample to use msal.js 2.0 someday.
