### ISSUE TITLE
Is the excel-shared-runtime-scenario still in preview?

### ISSUE THREAD

**Issue by robkott** [OfficeDev/PnP-OfficeAddins#101]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

The readme for excel-shared-runtime-scenario still says it relies on preview features:

Note: The features used in this sample are currently in preview and subject to change. They are not currently supported for use in production environments. To try the preview features, you will need to join Office Insider. A good way to try out preview features is by using an Office 365 subscription. If you don't already have an Office 365 subscription, you can get one by joining the Office 365 Developer Program.

Is this still true? Does this sample use RibbonApi1.1 ([https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/ribbon-api-requirement-sets])? Have these apis all reached general availability?

Thanks

**Comment by AlexJerabek** [comment]
Hi @robkott, 
The sample does use contextual tabs, which are currently in preview. I'll tag @Rick-Kirkham, in case there's more to say about the timeline of that feature.

Other parts of the sample are in general availability. Is there a specific API you're wondering about?

**Comment by robkott** [comment]
One of the things I am struggling with is knowing what APIs I am using and what version of the API i am using. Can I determine that from the manifest? Or is it based on the office-addin package versions?

**Comment by AlexJerabek** [comment]
Sure. Let me add @davidchesnut to help address this for the PNP samples and determine how we can better convey this information.

**Comment by davidchesnut** [comment]
Thanks for catching this @robkott !

These samples are no longer in preview. I created PR #102 to fix this.
