### ISSUE TITLE
Office-Add-in-Microsoft-Graph-React Sample example - First try = Login is already in progress

### ISSUE THREAD

**Issue by inspiraller** [OfficeDev/PnP-OfficeAddins#104]
I have followed the instructions from here and registered an app via azure to test this Sample:
- link1: https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth/Office-Add-in-Microsoft-Graph-React
- link2: https://docs.microsoft.com/en-us/graph/auth-register-app-v2

1. **Register an application with the Microsoft Identity Platform**
- visit https://portal.azure.com/
- login with excel 365 acc
- [click ] on top left hand hamburger
- [select] - Azure Active Directory
- [scroll] to bottom of page to see icon - App registration
- [click] App registration
- [type name] Sample-Office-Add-in-Microsoft-Graph-React
- [select] - Accounts in any organizational directory
 - [keep] - Web
- [type - redirect uri] https://localhost:3000/login/login.html
- [click] - register

2. **Copy client id to put into login/login.ts**
- [copy] Client ID
- [paste] login/login.ts clientId

3. **certs - https://github.com/OfficeDev/generator-office/blob/master/src/docs/ssl.md#method-2-manually-install-the-certificate**
- cd to certs folder
```
cd Office-Add-in-Microsoft-Graph-React\certs
```
- [Dbl click] - ca.crt
- [click] Install certificate
- [Select] Local Machine
- [Select] Place all certificates in the following store
- [click] browse
- [Select] Trusted Root Certification Authorities
- [click] ok
- [click] next
- [click] Finish
```
The import was successful
```
You now have a self-signed certificate installed on your machine.

4. **run cmd as administrator: run node application**
```
yarn start
```
- Note: Did not opwn separate cmd window. Stayed in same.
5. **Open new cmd terminal - run sideload**
```
yarn run sideload
```
6. **in excel [click] - Open Add-in**
7. **[click - button] Connect to Office 365**
> errorMessage: login_progress_error message: Login_In_Progress: Error during login call - login is already in progress. errorCode: ClientAuthError: Login_In_Progress: Error during login call - login is already in progress. at AuthError (eval code:26:9) at ClientAuthError (eval code:106:9) at ClientAuthError.createLoginInProgressError (eval code:143:9) at UserAgentApplication.prototype.acquireTokenInteractive (eval code:333:13) at UserAgentApplication.prototype.loginRedirect (eval code:246:9) at Office.initialize (eval code:50:13) at Anonymous function (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js:1782:41) at validateFunction (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js:306:21) at LoadScriptHelper.prototype.waitForFunction (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js:318:13) at appReady (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js:1778:25) .

I have looked in the other stackoverflow questions and github, and there is not a solution to this problem. Any advice.
thanks

**Comment by eirikb** [comment]
Hi  
I've found a way to trigger this consistently after the Add-in is setup. And a workaround to bypass the error.

### Triggering the error
If I change (or remove) the **Redirect URIs** in **SPA** setup in **Authentication** in the **AAD App** I can trigger the usual 
> Sorry, but we’re having trouble signing you in.
> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application

error, as expected.
Now I can close the popup, change the **Redirect URIs** back to the valid URI and trigger login (**signInO365**) which should work, but I get the error as described in this issue. 

### Bypass error

To bypass this I clear **cookies** (on my domain), not `localStorage` or `sessionStorage`, but cookies.  
MSAL will create a bunch of **non**-HttpOnly cookies, and by clearing these the login will work as expected.  
There is a bug in the sample, where the `Promise` from [`msalInstance.loginRedirect`](https://github.com/OfficeDev/PnP-OfficeAddins/blob/master/Samples/auth/Office-Add-in-Microsoft-Graph-React/login/login.ts#L32) is ignored, this is where I add a `catch` and do something like this: https://stackoverflow.com/a/179514 .
I tried to find some "clear" method in MSAL, but didn't see anything.

**Comment by davidchesnut** [comment]
Hi @inspiraller and @eirikb,

Yes, following @eirikb's repo steps I see this same problem. @inspiraller does clearing the cookies fix the issue for you? I'm checking with the team to see if there's a better solution. Thanks!

**Comment by davidchesnut** [comment]
Hi @inspiraller,

I apologize as I missed an important detail in your repo steps. Your steps indicate that you configured a **web** redirect. You need to use an **SPA** redirect since this sample is a single-page application. You can configure this from the **Redirect URIs** links on the **Overview** page in your App registration on the Azure portal. This will take you to the **Platform configurations** page where you can **Add a platform** and then choose **Single-page application**.

Hope this helps,
David
