### ISSUE TITLE
Office Add-In Built Upon Angular that Uses a Shared JavaScript Runtime

### ISSUE THREAD

**Issue by Alex-Willenbrink** [OfficeDev/PnP-OfficeAddins#105]
I'm trying to generate a simple excel office add-in with a shared JavaScript runtime that uses Angular instead of React but can't seem to get it to work. The office add-in DOES work before I try to implement the JavaScript shared runtime.

I've gone through and applied all the relevant steps in this [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime) but nothing seems to work as soon as I add this to the manifest.xml:

```
<Runtimes>
      <Runtime resid="ContosoAddin.Url" lifetime="long" />
</Runtimes>
```

My (naive) Assumption: If the source locations for the taskpane and commands were initialized in the same html file (index.html) and the above xml was included to the manifest.xml, the JavaScript shared runtime would be magically generated.

Questions:
- Why is this assumption incorrect?
- How can I generate the shared javascript runtime in an angular project?

Here's my [repo](https://github.com/Alex-Willenbrink/angular-shared-runtime) for reference.

Thanks in advance!

**Comment by davidchesnut** [comment]
Hi @Alex-Willenbrink, thanks for including the repo location of the code. Looking at the manifest, you need to be sure you always use the same resource id to refer to the shared runtime. For example:
`<Runtime resid="ContosoAddin.Url" lifetime="long" />`
...
`<FunctionFile resid="ContosoAddin.Url"/>` 

Your manifest is using Commands.Url for FunctionFile. When the resource ids differ by name, the shared runtime won't load (even if they point to the same html file to load.)

BTW: We updated guidance recently in [how to configure your add-in to use the shared runtime](https://docs.microsoft.com/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime). I recommend taking a look. for example, you'll want to include the `<Set Name="SharedRuntime" MinVersion="1.1"/>` requirements.

Hope this helps,
David
