### ISSUE TITLE
Example does not work on MacOS Big Sur

### ISSUE THREAD

**Issue by gpowork** [OfficeDev/PnP-OfficeAddins#116]
**URL of sample**

_https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-global-state_

**Describe the bug**

_Example does not show custom formula in excel on MacOS Big Sur (did not test on other versions). Task pane works well._

**To Reproduce**

1. _Go to 'root folder of example'_
2. _Run 'npm run start'_
3. _Excel appears put into any cell '=CONTOSO.GETVALUEFORKEYCF("1")'_
4. _See error_

**Expected behavior**

_It should work as described in the example Readme._

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [Mac]: Mac
- Host [Excel]: Excel
- Office version number: 16.45
- Operating System: macOS Big Sur 11.1
- Browser (if using Office Online): ______

**Additional context**

_Add any other context about the problem here._

**Comment by davidchesnut** [comment]
Hi @gpowork, thanks for reporting this.

We tried the repo steps on macOS Big Sur, but the sample is working correctly for us. You might try [clearing the Office cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-mac) to see if that helps. Or can you follow up with more details about the error you are seeing?

Thanks!
David
