### ISSUE TITLE
"cannot be displayed in a frame" error

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/PnP-OfficeAddins#130]
Is there a way to update the web.config of an Outlook for web add-in to prevent the "... cannot be displayed in a frame" error?

Thanks

**Comment by exextoc** [comment]
Can you clarify what the "... cannot be displayed in a frame" error is? (do you have a screenshot of the issue) Also what version of Outlook are you on? OWA, Mac, Desktop Outlook etc.

**Comment by elthombre** [comment]
Hi it was OWA but I'm not on that project any longer.

**Comment by exextoc** [comment]
Can you share the scenario when you are seeing this issue? Also a screenshot of the error will be helpful.

**Comment by elthombre** [comment]
I'm not on that project any longer, sorry
