### ISSUE TITLE
Walkthrough?

### ISSUE THREAD

**Issue by johnaweiss** [OfficeDev/PnP-OfficeAddins#132]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

i feel overwhelmed by this resource. Is there a very simple, step-by-step walkthrough to get started?

thx

**Comment by aafvstam** [comment]
What are you looking for? Word, Excel ... other?

This would be the ultimate starting point:
https://docs.microsoft.com/en-us/office/dev/add-ins/overview/learning-path-beginner

**Comment by johnaweiss** [comment]
Excel

**Comment by aafvstam** [comment]
Ok, starting with the link above your next step would be:
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator
and
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial

As suggested above, you are better served asking implementation related questions on StackOverflow tagging it with [officedev] and/or [office-js] :
https://stackoverflow.com/questions/tagged/officedev
https://stackoverflow.com/questions/tagged/office-js
The team is actively monitoring that for questions like this.

I'll close this one here as GH is the place to submit/handle repo related issues.
