### ISSUE TITLE
Outlook signature: The operation on mailbox failed because it's out of the current user's write scope. 

### ISSUE THREAD

**Issue by vdboots** [OfficeDev/PnP-OfficeAddins#139]
When i try to sideload the app on a non admin user. Or publish it to a user as test by using exchange Add-ins it won't come forward. 

The error message i get is: 
`Outlook signature: The operation on mailbox failed because it's out of the current user's write scope. `

it seems to only work on domain admins.

**Comment by JuaneloJuanelo** [comment]
Hello Vincent (@vdboots )  can you add more info just to make sure we diagnose properly:
1. Exchange configuration (it is online? on Premise and what version
2. In what platform you are trying this? And what version.
3. How are you deploying the add-in?  is the person receiving the add-in has the minimal client requirements?
