### ISSUE TITLE
Unathorized when save attachmment on outlook web

### ISSUE THREAD

**Issue by theogumilang** [OfficeDev/PnP-OfficeAddins#178]
Hi, So I tried to run this repository
https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO.
I already set all the requirements like app registration etc. And it's already running on my outlook desktop. But when I tried to run the add-in on the Outlook Website I always get the 401 Unauthorized code.  the message is always
`Authorization has been denied for this request.`
When I see on my chrome dev tools it already sending the authorization token on the headers. But why it always returns the 401 status code.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @theogumilang.

@ElizabethSamuel-MSFT, can you please take a look?

**Comment by davidchesnut** [comment]
Hi @theogumilang,

Can you provide any more information about the call returning the 401? Which API is it calling (like /api/saveAttachments?) Which headers is the call passing? 

Thanks!
David

**Comment by kudecha** [comment]
Hi David,
I am facing the same issue as described above.
I can successfully install the Outlook add-in and invoke it as well, which shows list of attachments.
However,
After selecting an attachment and clicking 'Save selected' button, it fails with 401 Unauthorized response.
Message is: Authorization has been denied for this request.
I can see 'Authorization' header with 'Bearer {accesstoken}' and request payload with attachment and message ids.
C# breakpoint on SaveAttachmentsController Post action is not hit.

The only workaround is:
If I uncomment [Authorize] attribute on SaveAttachmentsController, it would hit 'Post' function.
But again it won't find ClaimsPrincipal.Current, so it would not proceed further.
Instead, it would go through the Login then Authorize process if I click 'Allow' on the warning popup in add-in.

I am using Chrome as browser, in case it helps.

Would you please look into this when you find time?
Thanks,
Jay

**Comment by davidchesnut** [comment]
Hi @kudecha,

I assume you are just running the sample with no modifications (other than configuring it with an Azure registration?) I think the audience value in the token is different when you get the user token from getAccesstoken() versus signing in the user with a form. getAccessToken will set the audience to your app registration as the intended audience. Signing in the user sets the audience value to the service id the user wants access to. This might be throwing off the validation of the [Authorize] tag. Let me check into this and get back to you.

Thanks!
David

**Comment by kudecha** [comment]
Hi David,

Any updates on this issue?

I had a typo in my previous message as well.
old: If I uncomment [Authorize] attribute on SaveAttachmentsController, it would hit 'Post' function.
NEW: If I **_comment_** [Authorize] attribute on SaveAttachmentsController, it would hit 'Post' function.
so,
on commenting authorize attribute, it would hit POST function, but again it would show popup on app, where I need to click 'Allow' so it opens an external popup for me to login.

How do I fix the behaviour and get 'SaveAttachments' work without me logging in all the time (and keep authorize attribute as well)?

Thanks,
Jay

**Comment by davidchesnut** [comment]
Hi @kudecha,

Yes, if you comment out the [Authorize] attribute then the auth token is not validated (so the call will go through as you see.) Obviously we want to validate any tokens coming in to the server.  Since you can see the bearer token, drop the token string value into this site: https://jwt.ms/  This will decode it so you can see all the claims. There should be an audience (aud) claim and it should have the same ID value as your app registration client value (this should be the behavior for the token from getAccesstoken()). If it does not match there is most likely something misconfigured in the Azure app registration such as a wrong ID specified somewhere.

(BTW: Ignore my previous comment on audience mismatches. That won't apply in this scenario.)

Thanks!
David

**Comment by davidchesnut** [comment]
Closing this issue as the conversation has moved to #187
