### ISSUE TITLE
outlook-set-signature. npm ron build not working as aspected.

### ISSUE THREAD

**Issue by vdboots** [OfficeDev/PnP-OfficeAddins#180]
> Note: This template is only for reporting bugs about samples in this repo. If you have a product bug to report about Office web Add-ins, please submit the issue at [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues/new). This will help us respond to your issue faster.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

**outlook-set-signature**

**autorun not working anymore after running build and uploading it.**

After running npm run build and uploading it to azure storage or other parts. The solution is not working anymore. After the polifill has done its job  on outlook for desktop it is not working 

**Expected behavior**

Autorun should give same result as in produtction build as dev

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: online and desktop
- Host [Excel, Word, PowerPoint, etc.]: outlook
- Office version number: 2105
- Operating System: Windows 10
- Browser (if using Office Online): Edge chrome

**Comment by AlexJerabek** [comment]
Hi @vdboots, 

Thanks for reporting this. @ElizabethSamuel-MSFT, can you please take a look.

**Comment by ElizabethSamuel-MSFT** [comment]
@vdboots Can you try the instructions found in the following article if you haven't already? For example, your manifest should no longer reference localhost.

[Publish an add-in developed with Visual Studio Code](https://docs.microsoft.com/office/dev/add-ins/publish/publish-add-in-vs-code)

Let us know if that helps.

Thanks.
