### ISSUE TITLE
"Office.js has not fully loaded" when debugging Outlook-Add-in-SSO sample in Outlook for Windows

### ISSUE THREAD

**Issue by elegault** [OfficeDev/PnP-OfficeAddins#192]
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO

When side-loading the manifest (or directly uploading the manifest on the "My add-ins" page) and starting Outlook for Windows, the task pane loads blank (with script errors in Visual Studio and from the F12 Chooser app's debugger).

**To Reproduce**

1. Start Visual Studio Project with "Office Client" selected as startup in the Properties pane for the manifest project
2. Load the add-in in Outlook for Windows

**Expected behavior**

The add-in loads without issues.

**Screenshots**

![image](https://user-images.githubusercontent.com/4130365/127569582-9e109e30-40ff-44cf-ac2a-bbff20faa73e.png)

![image](https://user-images.githubusercontent.com/4130365/127569832-83853cbf-9a5c-4437-8262-f65ab0ab717e.png)

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: Microsoft Outlook for Microsoft 365 MSO (16.0.14228.20200) 64-bit
- Operating System: Windows Server 2019 (Version 1908; OS Build 17763.2061)
- Browser (if using Office Online): ___n/a___

**Comment by davidchesnut** [comment]
Hi @elegault,

In the screen shot there is a missing semicolon after the brace on line 154. Probably was accidentally deleted or something. But please let us know if there are still issues with this sample.

Thanks!
David
