### ISSUE TITLE
Samples/auth/Office-Add-in-NodeJS-SSO/SSOAutoSetup fail on npm start

### ISSUE THREAD

**Issue by camnealie** [OfficeDev/PnP-OfficeAddins#201]
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO

**Describe the bug**

Running through the steps: 
1. npm install works (ofc)
2. npm run configure-sso works (very clever btw)
3. npm start fails!

Error: Cannot find module '/Users/camnealie/Downloads/PnP-OfficeAddins-main/Samples/auth/Office-Add-in-NodeJS-SSO/SSOAutoSetup/src/bin/www'

The folder it's looking for /src/bin/www simply doesn't exist in the repo - I'm guessing there's a compile process that's not configured correctly?

**To Reproduce**

Follow the install steps outlined in the readme

**Expected behavior**

Compiling and sideloading the addin to excel

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: Mac, office online
- Host [Excel, Word, PowerPoint, etc.]: vsCode
- Office version number: Online
- Operating System: 10.15.7
- Browser (if using Office Online): Chrome 

**Additional context**

_Add any other context about the problem here._

**Comment by AlexJerabek** [comment]
Hi @camnealie,

I tried reproing this and had the same issue. What's the output of your `npm run configure-sso works` step?

**Comment by davidchesnut** [comment]
Hi @camnealie,

Looks like we forgot to copy the bin folder over from the old project when we moved the sample to this repo. You can find and copy the correct files at https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/tree/master/SSOAutoSetup/src/bin

I'll submit a PR to fix this soon. Thanks!

**Comment by camnealie** [comment]
Hey just confirming it works with the copied bin folder, thanks for the fast reply on this
