### ISSUE TITLE
Minimize/Expand taskpane (Office add-in Excel) feature when only one taskpane is open/active

### ISSUE THREAD

**Issue by cgaranip** [OfficeDev/PnP-OfficeAddins#209]
Hi,

In the sample code: PnP-OfficeAddins/Samples/excel-keyboard-shortcuts/

I would like to know how the minimize/expand icon appeared on the side vertical bar? is it in-built functionality of using "excel on web"?
Attached the picture with highlight to know what I mean. 
![MinimizeExpand](https://user-images.githubusercontent.com/85703760/134121725-6d8eadf4-45fe-429e-b32d-84f44d4faf5b.PNG)

in my local machine, it did not appear the way it is in your sample. attached the picture. 
![MPSTaskPane](https://user-images.githubusercontent.com/85703760/134122171-48753039-85f4-45c8-9c3a-a9bd2c19c73c.PNG)

can you please give me pointers how to get side bar with an icon to show/hide when only one task pane is open. 

FYI after upgrading excel office app and shared runtime is used, then multiple icons appear on the sidebar (vertical) but when only one taskpane is open sidebar does not appear and not able to hide/show the taskpane. Attached the pic. 
![MPSTaskPaneMultiple](https://user-images.githubusercontent.com/85703760/134122464-65c3a4ff-8d00-4e3d-8045-0781d943e850.PNG)

Using VS 2019, office 365 version 1202.

**Comment by AlexJerabek** [comment]
Hi @cgaranip,
I don't believe that element of the task pane layout is configurable by an add-in. @Rick-Kirkham, could you please confirm?

**Comment by cgaranip** [comment]
> Hi @cgaranip,
> I don't believe that element of the task pane layout is configurable by an add-in. @Rick-Kirkham, could you please confirm?

so are you saying that side bar with hide/show icon might be default only for excel on the web? not available for stand alone local excel apps using office add-ins?

**Comment by AlexJerabek** [comment]
Yes, how the add-in task pane is contained and displayed within Excel is determined by Excel. The content of the task pane is controlled by your add-in.

**Comment by Rick-Kirkham** [comment]
Alex is correct. That part of the UI is not configurable by the add-in developer. I'll close this question for now, but you can still comment if you have further questions on this issue.
