### ISSUE TITLE
ExtendedOverrides element of Manifest error

### ISSUE THREAD

**Issue by cgaranip** [OfficeDev/PnP-OfficeAddins#210]
Hi,

Sample Code:  PnP-OfficeAddins/Samples/excel-keyboard-shortcuts/

When creating an Office.js Add-in in Visual Studio 2019, adding the ExtendedOverrides element to the manifest, in order to be able to add keyboard shortcuts, the following error is thrown:

Error: **The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'ExtendedOverrides' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'. List of possible elements expected: any element in namespace 'http://www.w3.org/2000/09/xmldsig#'.**

Using VS 2019, office 365 version 1202.

Followed the steps as in https://docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts

Attached the manifest file in txt format. 
[manifest.txt](https://github.com/OfficeDev/PnP-OfficeAddins/files/7200745/manifest.txt)

Please help how to fix the issue. Di I need to update the xsd file manually to add the elements? or any upgrade to the software installed (VS 2019) required?

**Comment by aafvstam** [comment]
The element used "ExtendedOverride" is optional but if is used it should come after "VersionOverrides"
[ExtendedOverrides Element](https://github.com/OfficeDev/office-js-docs-pr/blob/1983a874eb2e89ba522aeffcb8e36d2f5c8d66ac/docs/reference/manifest/extendedoverrides.md#can-contain
)
In your case this looks OK:
[Work with Extended Overrides of the manifest](https://github.com/OfficeDev/office-js-docs-pr/blob/1983a874eb2e89ba522aeffcb8e36d2f5c8d66ac/docs/develop/extended-overrides.md)

There are a couple of options here that can be the cause:

- Validate the Manifest to the latest version
[Validate an Office Add-in's manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest)

- The XSD used to validate against is outdated
[Update to the latest Office JavaScript API library and version 1.1 add-in manifest schema](https://github.com/OfficeDev/office-js-docs-pr/blob/1983a874eb2e89ba522aeffcb8e36d2f5c8d66ac/docs/develop/update-your-javascript-api-for-office-and-manifest-schema-version.md)
- The JSON used is invalid
Check with [Extended Manifest JSON](https://developer.microsoft.com/en-us/json-schemas/office-js/extended-manifest.schema.json)

You should not need to update the xsd manually, but my guess is that your tools (VS/Office) are looking at an outdated version of the schema. The above guidelines can help tracking down the source of the issue.

Added several resources that you might already have checked, but for an outsider reading the issue the context might help to understand the issue.

Please share your findings, if it didn't fix the issue let us know and we will look for other options.

**Comment by cgaranip** [comment]
Thank you for your reply!!

my office.js and VS 2019 are up to date. I tried links as mentioned above as well. but it did not resovle the issue.

I am trying to add keyboard short cuts to my excel add-in to show/hide taskpane. So I tried to add extendedoverrides element to my manifest file and it throws above mentioned error. I checked one of the xsd files TaskPaneAppVersionOverridesV1_0.xsd file my manifest file is referring to and I do not find ExtendedOverrides element. I checked other xsd files as well but no file has that 'ExtendedOverrides' element defined. is there a way to have access to xsd files that have ExtendedOverrides and Supportpinning elements so i can udpate my xsd files.

**Comment by cgaranip** [comment]
Resolved the issue from another source. Thank you for all your help!! appreacite it!
xsd was not up to date with ExtendedOverrides element for VS 2019 installation. 
Please refer to the resolution as below
https://github.com/OfficeDev/office-js/issues/2132

Please close the issue.
