### ISSUE TITLE
Missing bin/www file in Before and Complete folders of Office-Add-in-NodeJS-SSO sample

### ISSUE THREAD

**Issue by reallyblackbuffalo** [OfficeDev/PnP-OfficeAddins#215]
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO

**Describe the bug**

The package.json file's start script references ./bin/www in both the Before and Complete folders, but that file isn't there. In the SSOAutoSetup folder the start script references src/bin/www (since the folder structure is slightly different) and it's there. I'm assuming the same file would work in the other folders with little to no modification, but I figured I'd report this since I noticed it while trying to follow the tutorial for the sample.

**To Reproduce**

1. Look inside the Before and Complete folders for bin/www; it's not there.

**Expected behavior**

bin/www should be there so that the web server can be started

**Screenshots**

N/A

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: Any
- Host [Excel, Word, PowerPoint, etc.]: Any
- Office version number: Any
- Operating System: Any
- Browser (if using Office Online): Any

**Additional context**

N/A

**Comment by davidchesnut** [comment]
Thanks @reallyblackbuffalo, I just merged a PR to restore those files.
