### ISSUE TITLE
SSO for outlook add-in

### ISSUE THREAD

**Issue by sandeepsa** [OfficeDev/PnP-OfficeAddins#58]
**Is your feature request related to a problem? Please describe.**

Trying to implement SSO flow, please share any guidelines to implement Single Sign On.  

**Describe the solution you'd like**

Should be able to get access token using SSO, and save email to SharePoint location. Current implementation has popup to get access token. 

**Describe alternatives you've considered**

If we have to use popup for authentication, is there a best to avoid popup and sign in silently. 

**Additional context**

_Add any other context or screenshots about the feature request here._

**Comment by Rick-Kirkham** [comment]
We have extensive documentation for SSO at this article and it's peer articles: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins

We have these two samples:
https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO
https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO

**Comment by sandeepsa** [comment]
Thank you
