### ISSUE TITLE
Excel-custom-functions instructions result in Add-In Error

### ISSUE THREAD

**Issue by connerk** [OfficeDev/PnP-OfficeAddins#60]
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/blob/0354c2b155b52e4c6e37eee93b2bc62629256d80/Excel-custom-functions/AzureFunction/README.md

**Describe the bug**

When following the instructions to deploy the sample, _Build and run the custom function_ item 3 is to run `npm run start`
upon this, webpack compiles, excel opens, but the excel add-in side window states 

   ADD-IN ERROR
   This add-in is no longer available: add-ins inserted during development are only available during debugging from Visual Studio. Please open your project in Visual Studio and re-run your application, or deploy your add-in into a valid catalog and re-inser

**To Reproduce**

Follow the instructions until the event is reproduced

**Expected behavior**

I should be able to continue to the next step of the instructions

**Screenshots**

![image](https://user-images.githubusercontent.com/1771679/71928956-6ed64380-314d-11ea-900f-823b7ca5caf6.png)

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: 1902
- Operating System: Windows 10
- Browser (if using Office Online): ______

**Comment by davidchesnut** [comment]
Hi @connerk, thanks for raising this issue! We're taking a look.
Thanks,
David

**Comment by davidchesnut** [comment]
Hi @connerk, One thing that will cause this error is if the manifest.xml is invalid. You might try running a diff of the manifest you have against the original from the repo and see if you can spot anything that might have changed. 

You can also run the following command which will validate the manifest file in your project to see if their are any errors. (this is from [Validate an Office Add-in's manifest](https://docs.microsoft.com/office/dev/add-ins/testing/troubleshoot-manifest))

`npx office-addin-manifest validate MANIFEST_FILE`

Hope this helps,

Thanks,
David

**Comment by davidchesnut** [comment]
Hi @connerk, I haven't seen any update on this issue in a while, so I will close it for now. If you are still running into any issues with the project, please feel free to reopen this issue.

Thanks!
David
