### ISSUE TITLE
How to download sample?

### ISSUE THREAD

**Issue by Buzzardbait** [OfficeDev/PnP-OfficeAddins#62]
I don't understand how to download the sample files. The usual Clone and Download buttons are missing.
Thanks

**Comment by davidchesnut** [comment]
Hi @Buzzardbait, Right now you have to clone or download the entire repo. Then browse to the folder of the sample you want to work with. I'll do a little checking to see if there's a way to make the download process more granular to each sample, but I'm not sure how well it will work on a GitHub repo.  Thanks!

**Comment by Buzzardbait** [comment]
Oh! How dumb of me! Please don't go to that trouble I can easily extract it from the download.
Thanks, but I may have more questions when I try to run it because I'm not experienced with Visual Studio 2019 :-)

**Comment by davidchesnut** [comment]
:-) no worries. I'm happy to help with any questions.
