### ISSUE TITLE
Office Addin MS Graph ASP.NET 

### ISSUE THREAD

**Issue by amandalegere8** [OfficeDev/PnP-OfficeAddins#74]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

C:\Office-Add-in-Microsoft-Graph-ASPNET\Office-Add-in-Microsoft-Graph-ASPNETWeb\Models\SessionToken.cs

Says I am missed a reference to JwtSecurityToken when I try to run. Did I do something wrong?

**Comment by Rick-Kirkham** [comment]
Please provide more details. What are the exact steps that lead to the error. Where do you see the error? (E.g., in Visual Studio?)

**Comment by amandalegere8** [comment]
Yes its in visual studio.

I commented out the block of code until I didn't have an error anymore.
When I run (F5) the project I still get a problem occurred while trying to
reach this add-in.

**Comment by Rick-Kirkham** [comment]
What is the exact error that you see? Can you provide a screen shot?
What is the block of code that you commented out?
Does the sample still work with the code commented out?
