### ISSUE TITLE
Office.ASP.NETCoreReactAddins uses .Net Core 2.2 Runtime which is EOL

### ISSUE THREAD

**Issue by MarkIannucci** [OfficeDev/PnP-OfficeAddins#77]
.Net Core 2.2 was EOL 12/23/2019.  It would be great if someone can update the sample to 3.1.

**Comment by aafvstam** [comment]
Well, you are in luck ... I already did the work and created a PR #75 for this [here](https://github.com/OfficeDev/PnP-OfficeAddins/pull/75/commits/3928f5abde41d1914e10dd4d776c57284bb3992c) and waiting for it to be merged. Initially only upgraded the TypeScript part as I wanted to get this pulled in before putting in more work to also update the JaveScript part. The PR has been sitting here now for a couple of weeks without any interaction so not sure what is going on. Maybe they plan to surprise us at Build 2020 next week ;-)

**Comment by MarkIannucci** [comment]
@aafvstam , thank you.  I am in luck; I'll use your fork until the PR gets merged.

**Comment by Rick-Kirkham** [comment]
Sorry for the delay. The PR is now merged.
