### ISSUE TITLE
excel-shared-runtime-scenario sample issues

### ISSUE THREAD

**Issue by adim1973** [OfficeDev/PnP-OfficeAddins#81]
**URL of sample**

[sample link](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario)

**Describe the bug**

1. Ribbon buttons (commands) are always enabled.
2. The Sum Command doesn't work and crashes the add-in (after pressing Sum the add-in is not working anymore).
3. Running the tasks "tsc: watch - tsconfig.json" or "tsc: build - tsconfig.json" in VS Code throws two errors.

- The add-in loads and works fine after running `start npm start` and `npm run sideload` from command line (as per [Build and run the solution](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario#build-and-run-the-solution) paragraph), except the above issues 1 and 2.
- I'm trying to run (and debug) it from VS Code, but issue 3 happens.

**Expected behavior**

1. Some ribbon buttons should toggle their enable state, as per description.
2. Sum functionality should work as described.
3. I would appreciate any help in running this from VS Code.

**Screenshots**

Buttons always enabled
![image](https://user-images.githubusercontent.com/5249431/82726620-1fed0d00-9cee-11ea-8afa-b2f4674b1b62.png)

Add-in error after pressing Sum button
![image](https://user-images.githubusercontent.com/5249431/82726652-4ad76100-9cee-11ea-9495-48d115b21020.png)

Available tasks in VS Code
![image](https://user-images.githubusercontent.com/5249431/82726670-5aef4080-9cee-11ea-966c-8a565873ac30.png)

Errors after running "tsc: watch - tsconfig.json"
![image](https://user-images.githubusercontent.com/5249431/82726690-6d697a00-9cee-11ea-99cb-d60d753d6762.png)

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: Excel for Microsoft 365 MSO (16.0.12730.20252) 64-bit
- Operating System: Windows 10 Pro 1909 (18363.836) 64-bit
- Browser (if using Office Online): ______

Adrian

**Comment by EUOROSA** [comment]
Have you had any progress?

**Comment by adim1973** [comment]
None!

**Comment by Rick-Kirkham** [comment]
I'm trying to get you some help about this.

**Comment by jeremy-msft** [comment]
Hi @adim1973, thanks for your feedback.  It looks like you might be on an older version of Office that doesn't support this sample.  Could you please try again using the latest [Office Insider](https://insider.office.com/) build?

**Comment by adim1973** [comment]
I have updated to latest Excel available on normal channel (work 365 account here, so getting to Insider it's difficult) and also switched to Excel 32 bit and now everything works fine!

![image](https://user-images.githubusercontent.com/5249431/83722636-02049e00-a646-11ea-9e3d-11557c24ea2b.png)

Maybe switching to 32 bit was also helpful, don't know for sure.

Any suggestion on how to run and debug this from VS code?

**Comment by jeremy-msft** [comment]
It should work the same on 64-bit, so it's likely the latest update that resolved your issue.  Please feel free to switch over to 64-bit and let us know if you run into the same problem again.

Shared runtime will currently run using IE 11 on Windows (more details [here](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)).  Please see [this article](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10#when-the-add-in-is-running-in-internet-explorer) for currently supported IE 11 debugging options.

**Comment by topkoong** [comment]
It works fine on Office 365 Insider Fast Version for Mac; however, it's not working on Office Online, and a single-line ribbon is not enabled yet.
