### ISSUE TITLE
excel-shared-runtime-scenario: Taskpane loads wrong

### ISSUE THREAD

**Issue by EUOROSA** [OfficeDev/PnP-OfficeAddins#82]
Hi, could you help me?
When you click to show the taskpane, a small taskpane shows in the corner.
And this is happening with my application too.

![image](https://user-images.githubusercontent.com/63984627/83218022-766da780-a143-11ea-82e5-fafbb6f31389.png)

Every time I have that issue, Edge Devtools shows two line.
![image](https://user-images.githubusercontent.com/63984627/83218684-cef17480-a144-11ea-8f41-82276cce81da.png)

To work, I always need to start with a ribbon button xsi:type="ShowTaskpane", but in my application all buttons are xsi:type="ExecuteFunction".

**Comment by EUOROSA** [comment]
I was using Version 2005 (Build 12827.20210) and it happens to show small. So I downgraded to Version 2004 (Build 12730.20352) and the Taskpane worked, but now all the Ribbon buttons (commands) are always enabled.

![image](https://user-images.githubusercontent.com/63984627/83330489-a0b78600-a265-11ea-99ef-57788904fb75.png)

I tried different versions and always the same results.

Please, could you fix this?

**Comment by jeremy-msft** [comment]
Hi @EUOROSA, thanks for your feedback.  It looks like you might be on an older version of Office that doesn't support this sample.  Could you please try again using the latest [Office Insider](https://insider.office.com/) build?

**Comment by EUOROSA** [comment]
I'm already using Office Insider and updated to June 03, 2020
Version 2006 (Build 13001.20002). The small taskpane in the corner continues.

I'm using the Office.JS: https://appsforoffice.microsoft.com/lib/1/hosted/office.js

**Comment by adim1973** [comment]
It works fine for me (normal size taskpane, buttons toggle their state) with Excel 16.0.12827.20200 32 bit. Check the bitness of your Excel , that might me the issue.

**Comment by EUOROSA** [comment]
Thanks.
It works fine with Excel version 2005 (Build 12827.20268)(16.0.12827.20200 32 bit) by update normal monthly channel, but it caused a slight bug on the layout page. Note: this version opens with IE11 and debug using C:\WINDOWS\System32\F12\IEChooser.exe.

For Excel version 2005 (Build 12827.20268)(16.0.12827.20200 32 bit) by update Office Insider Current Channel (Preview), **It doesn't work,** I think because the taskpane page opens with MS Edge.

![image](https://user-images.githubusercontent.com/63984627/83762944-822f0180-a64e-11ea-95b9-dca449d92bae.png)
![image](https://user-images.githubusercontent.com/63984627/83762583-12207b80-a64e-11ea-90fd-b3a6920a650f.png)

I tried with several versions, and it only worked with: version 2005 (Build 12827.20268)

- Version 2006 (Build 13001.20002)(Office Insider Beta Channel): not work 
- Version 2006 (Build 12930.20014)(Office Insider Beta Channel): not work
- Version 2006 (Build 12920.20000)(Office Insider Beta Channel): not work
**- version 2005 (Build 12827.20268)(Office Insider Current Channel): not work**
- Version 2005 (Build 12827.20210): not work
- Version 2004 (Build 12730.20352): not work
- Version 2004 (Build 12730.20270): not work
- Version 2004 (Build 12730.20250): not work
- Version 2003 (Build 12624.20466): not work

======xxxx=====

I was having trouble downloading file (.xml and .zip) using the code below. The Taskpage opens with MS Edge and give me error: Not allowed to load local resource: blob:https://localhost:3000....

function saveAs(blob, filename) {
  if (typeof navigator.msSaveOrOpenBlob !== 'undefined') {
    navigator.msSaveOrOpenBlob(blob, filename);
  } else if (typeof navigator.msSaveBlob !== 'undefined') {
    navigator.msSaveBlob(blob, filename);
  } else {
    var elem = window.document.createElement('a');
    elem.href = window.URL.createObjectURL(blob);
    elem.download = filename;
    //elem.style = 'display:none;opacity:0;color:transparent;';
    (document.body || document.documentElement).appendChild(elem);
    if (typeof elem.click === 'function') {
      elem.click();
    } else {
      elem.target = '_blank';
      elem.dispatchEvent(new MouseEvent('click', {
        view: window,
        bubbles: true,
        cancelable: true
      }));
    }
    URL.revokeObjectURL(elem.href);
  }
}

But with the version 2005 (Build 12827.20268) opens with IE11, it solved.

**Comment by EUOROSA** [comment]
Hi,
I changed to the Office Insider Current Channel with the new Version 2005 (Build 12827.20320) (June 04, 2020) and It works fine.  For the slight bug on the layout page, I fixed it in the index.css.

======xxxx=====

For file downlad (saveAs) will always work due to note 3 below, i.e. it will always open with IE11.

https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
![image](https://user-images.githubusercontent.com/63984627/83933426-bdc8e900-a77e-11ea-8d14-eaf92cb277b0.png)
![image](https://user-images.githubusercontent.com/63984627/83933489-55c6d280-a77f-11ea-8643-83dfc63c2e2a.png)



Thanks for your help.
