### ISSUE TITLE
Issue with login popup with Outlook Client. Authentication popup not closed with Outlook Client

### ISSUE THREAD

**Issue by abhsha** [OfficeDev/PnP-OfficeAddins#84]
Login(Authentication) pop is not closing in Outlook Client. Same scenario worked fine in Outlook web app with Chrome,Edge.

Specifically observed with Outlook Client. Assuming due to "Office.context.ui.messageParent" not returning Error/Success data to parent window.

*Expected behavior**

Popup should close as user is authenticated.

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC 
- Host [Excel, Word, PowerPoint, etc.]: Outlook 
- Office version number: Outlook version( 2002)
- Operating System: Windows 10/ Server 2016
- Browser (if using Office Online): NA ( Outlook Client)

**Comment by davidchesnut** [comment]
Hi @abhsha,

I'm sorry for the late response on this issue. Can you confirm if you are still seeing this behavior? Also can you confirm if this is the sample where you see the bug behavior? https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET

I see the popup auth dialog closing correctly. So please let me know if I'm looking at the correct sample, or if I need to follow any specific steps to reproduce the behavior.

Thanks!
David
