### ISSUE TITLE
How to get started on a similar project?

### ISSUE THREAD

**Issue by EthanVaz** [OfficeDev/PnP-OfficeAddins#86]
I have tried the **excel-shared-runtime-scenario** sample from [Code.](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) and want to create a similar project from scratch using VS Code. How do I get started to create a similar project? I am interested in the Enable/Disable of ribbon items.

**Comment by AlexJerabek** [comment]
Hi @EthanVaz, 

If you're looking to make an Excel add-in using the shared runtime, please check out [Configure your Excel add-in to use a shared runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime).

If you're just looking to make a new Excel add-in from scratch, please visit [Build your first Excel task pane add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator).

I'm tagging @Rick-Kirkham for documentation links about controlling ribbon items.

**Comment by EthanVaz** [comment]
Hi @AlexJerabek,

Thanks for your reply. I have an existing project and I am trying the Enable/Disable feature. When the ribbon loads, I have it disabled but I am not able to Enable it via code. Office.ribbon.requestUpdate is executing but the ribbon is not getting enabled. I don't see any errors/exceptions. Not sure what's happening. If I can get some documentation on controlling ribbon items, that would be helpful.

**Comment by Rick-Kirkham** [comment]
Here is our article about enabling/disabling commands: [Enable and Disable Add-in Commands](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands)
