### ISSUE TITLE
Office.ribbon.requestUpdate() throws Uncaught (in promise) RichApi.Error

### ISSUE THREAD

**Issue by EthanVaz** [OfficeDev/PnP-OfficeAddins#95]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

I have created a sample project referring to https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

Manifest and the API to Enable/Disable ribbon was written referring to https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands

The API Office.ribbon.requestUpdate() is throwing an exception saying....

Uncaught (in promise) RichApi.Error: The API you are trying to use is not available. It may be available in a different scenario.
    at new RuntimeError (https://appsforoffice.officeapps.live.com/afo/lib/1.1/hosted/excel-web-16.00.debug.js:12735:36)
    at RequestContext.ClientRequestContext.processRequestExecutorResponseMessage (https://appsforoffice.officeapps.live.com/afo/lib/1.1/hosted/excel-web-16.00.debug.js:15900:24)
    at https://appsforoffice.officeapps.live.com/afo/lib/1.1/hosted/excel-web-16.00.debug.js:15805:43

I have https://appsforoffice.officeapps.live.com/afo/lib/1.1/hosted/office.debug.js in my html

Any idea what I am missing here?

**Comment by davidchesnut** [comment]
Hi @EthanVaz , it looks like the documentation is showing the wrong code for the API. I'm doing some more research to confirm. In the meantime you could try the following code to update the ribbon as shown in [this sample](https://github.com/OfficeDev/PnP-OfficeAddins/blob/master/Samples/excel-shared-runtime-scenario/utilities/office-apis-helpers.ts)
```typescript
// @ts-ignore
  OfficeRuntime.ui
    .getRibbon()
    // @ts-ignore
    .then(ribbon => {
      ribbon.requestUpdate({
        tabs: [
          { ...
```

Thanks,
David

**Comment by EthanVaz** [comment]
Tried and still the same error.

**Comment by davidchesnut** [comment]
Hi @EthanVaz Okay, I am able to reproduce this error if I introduce minor bugs in the manifest. For example, if <FunctionFile...> is not using the shared runtime you will see this error. Is it possible to share your manifest by posting it on your GitHub account somewhere? Or if you can share the add-in code I could try to repro the behavior from your code. Thanks!

**Comment by EthanVaz** [comment]
I need some time to upload my sample. Meanwhile, can you let me know the changes in the manifest which reproduced the error? Maybe I can try it and fix my issue.

**Comment by davidchesnut** [comment]
Hi @EthanVaz , sorry for late reply. You can see an example of a manifest using shared runtime [here](https://github.com/OfficeDev/PnP-OfficeAddins/blob/master/Samples/excel-shared-runtime-scenario/manifest.xml). Also the steps for configuring your manifest are in [Configure your Excel add-in to use a shared JavaScript runtime](https://docs.microsoft.com/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime). Thanks!
